#!/usr/bin/ruby

require "script/helpers"

puts <<ART

     ,o888888o.    8 888888888o
    8888     `88.  8 8888    `88.
 ,8 8888       `8. 8 8888     `88
 88 8888           8 8888     ,88
 88 8888           8 8888.   ,88'
 88 8888           8 888888888P'
 88 8888   8888888 8 8888
 `8 8888       .8' 8 8888
    8888     ,88'  8 8888
     `8888888P'    8 8888

That's git pull --rebase on everything you need!
ART

puts "\n[Robolectric]"
okay = system "(cd submodules/robolectric && git pull --rebase)"

bail_with "Robolectric" unless okay

puts "\n[Project]"
okay = system " git pull --rebase"

bail_with "Project" unless okay

